"""empty message

Revision ID: 504c5718a442
Revises: 4e206926a3c9
Create Date: 2020-09-21 15:38:37.155222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504c5718a442'
down_revision = '4e206926a3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_image')
    # ### end Alembic commands ###
