"""empty message

Revision ID: b13e58a198ed
Revises: 504c5718a442
Create Date: 2020-09-21 15:39:23.705302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13e58a198ed'
down_revision = '504c5718a442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
